# Generated by Django 5.2.7 on 2025-10-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, help_text="Optional. User's primary address.", null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional. Include country code (e.g. +1...).', max_length=15, null=True, verbose_name='phone number'),
        ),
    ]
